settings:
  protection_on_first_join: true
  time_protection: 120
  block_distance_to_see_walls: 5
  prote_players_can_enter_pvp_zones: false
  glass_walls_enabled: true
wand_selector:
  name: "&e&lSelector de zona"
  lore:
    - ""
    - "&fSelecciona la zona que va a ser"
    - "&fdestinada a pvp"
