main: me.dewrs.ProtectionPvP
name: ProtectionPvP
version: 1.3
api-version: 1.13
author: dewrs
depend: [ProtocolLib, PlaceholderAPI]

commands:
  protectionpvp:
    description: Main Command
    aliases: [protepvp]