main: me.dewrs.ProtectionPvP
name: ProtectionPvP
version: 1.5
api-version: 1.13
author: dewrs
depend: [ProtocolLib]
softdepend: [PlaceholderAPI]

commands:
  protectionpvp:
    description: Main Command
    aliases: [protepvp]